"""PRSE-OS semantic interfaces. Reference only; adapt names to your Harness."""
from typing import Protocol, Any, Mapping, Sequence

class PRSERuntime(Protocol):
    def read_package(self, package_uri: str) -> Mapping[str, Any]: ...
    def resolve_context(self, concern: str, scope: Sequence[str], permissions: Mapping[str, Any]) -> Mapping[str, Any]: ...
    def route_capability(self, work_item: Mapping[str, Any], quality_requirement: Mapping[str, Any]) -> Mapping[str, Any]: ...
    def execute_method(self, skill_id: str, inputs: Mapping[str, Any], context: Mapping[str, Any]) -> Mapping[str, Any]: ...
    def validate_artifact(self, artifact: Mapping[str, Any], profile: Mapping[str, Any]) -> Mapping[str, Any]: ...
    def emit_method_event(self, event: Mapping[str, Any]) -> str: ...
    def escalate(self, case: Mapping[str, Any]) -> Mapping[str, Any]: ...
